-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table book (
  id                            bigint generated by default as identity not null,
  created                       timestamptz,
  average_rating                float,
  rating_count                  integer,
  order_index                   bigint,
  title                         varchar(255),
  author                        varchar(255),
  publish_date                  varchar(255),
  good_reads_url                varchar(500),
  category                      varchar(255),
  sub_category                  varchar(255),
  isbn                          varchar(255),
  cover_image_url               varchar(255),
  description                   varchar(255),
  preview_url                   varchar(255),
  author_description            varchar(255),
  constraint pk_book primary key (id)
);

create table company (
  id                            bigint generated by default as identity not null,
  created                       timestamptz,
  name                          varchar(255),
  constraint pk_company primary key (id)
);


-- !Downs

-- drop all
drop table if exists book cascade;

drop table if exists company cascade;

